import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'

NOTE_FEATURES = ['pitch', 'delta', 'duration']
SEQ_LENGTH = 5
VOCAB_SIZE = 128
BATCH_SIZE = 32
LEARNING_RATE = 5e-3
MIN_DELTA = 0.001
NUM_FILES = 1
EPOCHS = 50
TEMPERATURE = 1.0
NUM_PREDICTIONS = 30
